### PR TITLE
Reformat message slightly

### PR DESCRIPTION
**Pull request by rivques**
Feel free to nix any of any of these, #s 2 and 3 especially are pretty much personal preference
* Add links to xkcd and explain xkcd
* Add comic number to title
* Move alt text below image and prefix it with "Alt: ", to imo read in a more comfortable order

### CODE REVIEW

**Comment by radioblahaj** [comment]
I think having it where the alt text is right now would work better. I tested it when I first made and it didn't quite flow propely

**Comment by radioblahaj** [comment]
Same with the title #

**Comment by radioblahaj** [comment]
The ExplaiXKCD part is a really nice change and additon thought thank you!!

**Comment by rivques** [comment]
Yeah, do whatever you want ofc, it's your bot. Glad I could be helpful on the linking though!

**Pull request merged**
